- label: 'Introduction'
  link: '/'
- label: 'Repository pattern'
  link: '/repository-pattern'
- label: 'Readability'
  items:
  - label: 'Naming'
    link: '/readability/naming'
  - label: 'Order'
    link: '/readability/order'
- label: 'Redux'
  items:
    - label: 'Concepts'
      link: '/redux/concepts'
    - label: 'Structure'
      link: '/redux/structure'
