# Sidebar navigation

# - label: 'Introduction'
#   link: '/'
# - label: 'Getting started'
#   link: '/getting-started'
# - label: Usage
#   items:
#     - label: 'Creating docs'
#       link: '/usage/creating-docs'
#     - label: 'Navigation'
#       link: '/usage/navigation'
#     - label: 'Shadowing'
#       link: '/usage/shadowing'
# - label: More
#   items:
#     - label: FAQ
#       link: /faq
#     - label: 'Github'
#       link: https://github.com/jpedroschmitz/rocketdocs

- label: 'Introduction'
  link: '/'
- label: 'Readability'
  items:
  - label: 'Naming'
    link: '/readability/naming'
  - label: 'Order'
    link: '/readability/order'
- label: 'Redux'
  items:
    - label: 'Concepts'
      link: '/redux/concepts'
    - label: 'Structure'
      link: '/redux/structure'
